(module
  (type $wire (struct (field $lo i64) (field $hi i64)))
  (import "zk" "mul" (func $mul (param i64 i64) (result i64)))
  (import "zk" "assert_one" (func $assert_one (param i64) (result i64)))
  (import "pre" "inv" (func $inv (param i64) (result i64)))
  (func (export "run") (param $a i64) (result i64)
    (local $inv i64)
    (local $y i64)
    (local $s (ref $wire))
    (local.set $inv (call $inv (local.get $a)))
    (local.set $s (struct.new $wire (local.get $a) (local.get $inv)))
    (local.set $y (call $mul (struct.get $wire $lo (local.get $s))
                             (struct.get $wire $hi (local.get $s))))
    (drop (call $assert_one (local.get $y)))
    (local.get $y)))
